import Head from 'next/head'
import React from "react";
import HomeBanner from "@/components/Banners/HomeBanner"
import { gql } from "@apollo/client";
import { getApolloClient } from "@/lib/apollo-client";


export default function Home() {


  return (
    <>
      <Head>
        <title>E-commmerce Local</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
      <main>
        <HomeBanner/>
        This is the home page
      </main>



    </>
  )
}

